name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *" # Every 3 hours

jobs:
  latest_release:
    # Don't run on private repo unless it is a PR or manual run
    if: (github.repository == 'invertase/firestore-ios-sdk-frameworks' && github.event_name == 'schedule') || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'

    name: "Latest Release"
    timeout-minutes: 120
    runs-on: macos-latest
    steps:
      # https://github.com/actions/checkout/releases
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: GIT Setup
        run: |
          git fetch --tags
          git config --global user.name 'Invertase Publisher'
          git config --global user.email 'oss@invertase.io'
          git remote set-url origin git@github.com:$GITHUB_REPOSITORY
      # https://github.com/webfactory/ssh-agent/releases
      - uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        if: ${{ github.repository == 'invertase/firestore-ios-sdk-frameworks' }}
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set Github Token Securely
        if: ${{ github.repository == 'invertase/firestore-ios-sdk-frameworks' }}
        run: echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
      # https://github.com/dart-lang/setup-dart/releases
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
      - run: cd ./.github/workflows/scripts && dart pub get
      - name: Process Latest Version
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: dart ./.github/workflows/scripts/framework-controller.dart
      - name: Report Failure Status
        # https://github.com/slackapi/slack-github-action/releases
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        if: failure()
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "https://github.com/invertase/firestore-ios-sdk-frameworks build failure for Firebase ${{ env.LATEST_FIREBASE_VERSION }} (job status: {{ job.status }})"
